[mgr]
show_hidden = true
linemode = "size"

[preview]
wrap = "yes"

[flavor]
dark = "neon"

[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Neovim" }
]

[[open.prepend_rules]]
url = "*.{txt,md,toml,yaml,yml,json,conf,sh,py,js,ts,lua}"
use = "edit"
